### ISSUE TITLE
Browsers default message is shown while reloading the page

### ISSUE THREAD

**Issue by maheshmgopi** [BezzubovEgor/react-router-navigation-confirm#14]
The default message "This page is asking you to confirm that you want to leave - data you have entered may not be saved." is shown in firefox on reloading the page after the custom dialog is shown for at least once.

**Comment by hoetmaaiers** [comment]
I think this happens because the `beforeunload` event is attached to the window: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event.

I was also looking into the reason why this is triggered even when the `when` clause is false...

**Comment by hoetmaaiers** [comment]
Currently on componentDidMount() the `beforeunload` event is attached, regardless of the when clause. 

My first thoughts are to conditionally attach the`beforeunload` event based on `props.when`. Maybe @BezzubovEgor can think along?

**Comment by munybt** [comment]
Hi @BezzubovEgor 
I would also like to have @hoetmaaiers 's suggestion implemented.
Also, I would event prefer to see the actual modal on `beforeunload`, instead of the browser's confirm window.
Is that possible?
I'm using the `NavigationConfirmModal` component.
Thanks in advance

**Comment by BezzubovEgor** [comment]
Hi @munybt. I will work on @hoetmaaiers's suggestion.
About the second item - as I remember there are were problems with a showing of modal on `beforeunload`, I will try to "hack" it, but can't promise anything =)
