### ISSUE TITLE
Navigation confirm does not take location search

### ISSUE THREAD

**Issue by itzik-bd** [BezzubovEgor/react-router-navigation-confirm#82]
The [isTheSameLocation](https://github.com/BezzubovEgor/react-router-navigation-confirm/blob/dbf3af0d7e3167b5269984ceadaa37569995ca97/src/lib/components/NavigationConfirm.tsx#L127-L127) current implementation is:
```
private isTheSameLocation = (nextLocation: Location): boolean => nextLocation.pathname === this.props.location.pathname;
```
However, it does not take into account the `location.search` so it misses blocking navigations.

Changing the implementation to the following fix this issue:
```
private isTheSameLocation = (nextLocation: Location): boolean => nextLocation.pathname === this.props.location.pathname && nextLocation.search === this.props.location.search;
```

**Comment by BezzubovEgor** [comment]
Thanks, I merged the PR created by you.
